
#### 1- [126219](https://github.com/python/cpython/issues/126219) - `tkinter.Tk` segfault with invalid `className`

```python

```

- Issue Number: 126219
- Date filed: 31/10/2024
- Date closed: 
- Kind: Segfault/Crash
- Configuration:
- Python versions: 3.12;3.13;3.14
- Status: open
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 2- [126220](https://github.com/python/cpython/issues/126220) - `_lsprof.Profiler._creturn_callback()` segfaults

```python

```

- Issue Number: 126220
- Date filed: 31/10/2024
- Date closed: 06/11/2024
- Kind: Segfault/Crash
- Configuration:
- Python versions: 3.12;3.13;3.14
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 3- [126221](https://github.com/python/cpython/issues/126221) - `sre_constants._makecodes` segfaults in JIT builds

```python

```

- Issue Number: 126221
- Date filed: 31/10/2024
- Date closed: 31/10/2024
- Kind: Segfault/Crash
- Configuration:
- Python versions: 
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 4- [126223](https://github.com/python/cpython/issues/126223) - `SystemError` caused by `_interpreters.create()` with invalid unicode argument

```python

```

- Issue Number: 126223
- Date filed: 31/10/2024
- Date closed: 31/10/2024
- Kind: SystemError
- Configuration:
- Python versions: 3.13;3.14
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 5- [126312](https://github.com/python/cpython/issues/126312) - GC aborts in debug no-gil build

```python

```

- Issue Number: 126312
- Date filed: 01/11/2024
- Date closed: 15/11/2024
- Kind: Abort/AssertionError
- Configuration:
- Python versions: 3.13;3.14
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 6- [126313](https://github.com/python/cpython/issues/126313) - `curses.napms()` aborts with a `SystemError`

```python

```

- Issue Number: 126313
- Date filed: 01/11/2024
- Date closed: 04/11/2024
- Kind: Abort/AssertionError
- Configuration:
- Python versions: 3.13;3.14
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 7- [126314](https://github.com/python/cpython/issues/126314) - Running `tracemalloc` in threads segfaults on no-gil

```python

```

- Issue Number: 126314
- Date filed: 01/11/2024
- Date closed: 14/03/2025
- Kind: Segfault/Crash
- Configuration:
- Python versions: 3.13;3.14
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 8- [126315](https://github.com/python/cpython/issues/126315) - `tracemalloc` aborts when run from threads in no-gil

```python

```

- Issue Number: 126315
- Date filed: 01/11/2024
- Date closed: 
- Kind: Abort/AssertionError
- Configuration:
- Python versions: 3.13;3.14
- Status: open
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 9- [126316](https://github.com/python/cpython/issues/126316) - `grp` is not thread safe

```python

```

- Issue Number: 126316
- Date filed: 01/11/2024
- Date closed: 21/11/2024
- Kind: 
- Configuration:
- Python versions: 3.13;3.14
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 10- [126341](https://github.com/python/cpython/issues/126341) - `SystemError` from calling `__iter__` on a released `memoryview`

```python

```

- Issue Number: 126341
- Date filed: 03/11/2024
- Date closed: 13/11/2024
- Kind: SystemError
- Configuration:
- Python versions: 3.12;3.13;3.14
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 11- [126366](https://github.com/python/cpython/issues/126366) - Abort in free-threaded build due to mutation of `ChainMap` of a `Counter` in threads

```python

```

- Issue Number: 126366
- Date filed: 03/11/2024
- Date closed: 18/04/2025
- Kind: Abort/AssertionError
- Configuration:
- Python versions: 3.13;3.14
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 12- [126455](https://github.com/python/cpython/issues/126455) - Calling many methods on `_ssl._SSLSocket()` segfaults

```python

```

- Issue Number: 126455
- Date filed: 05/11/2024
- Date closed: 06/11/2024
- Kind: Segfault/Crash
- Configuration:
- Python versions: 3.12;3.13;3.14
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 13- [126456](https://github.com/python/cpython/issues/126456) - `_pyrepl._minimal_curses.tigetstr` segfaults

```python

```

- Issue Number: 126456
- Date filed: 05/11/2024
- Date closed: 13/11/2024
- Kind: Segfault/Crash
- Configuration:
- Python versions: 3.13;3.14
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 14- [126461](https://github.com/python/cpython/issues/126461) - Calling `_pickle.load` with a `MagicMock` results in `SystemError`/aborts

```python

```

- Issue Number: 126461
- Date filed: 05/11/2024
- Date closed: 06/11/2024
- Kind: Abort/AssertionError
- Configuration:
- Python versions: 3.12;3.13;3.14
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 15- [126594](https://github.com/python/cpython/issues/126594) - Failed assertion in typeobject.c::wrap_buffer for `b"".__buffer__(-2**31 - 1)`

```python

```

- Issue Number: 126594
- Date filed: 08/11/2024
- Date closed: 24/11/2024
- Kind: Abort/AssertionError
- Configuration:
- Python versions: 3.12;3.13;3.14
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 16- [126595](https://github.com/python/cpython/issues/126595) - Failed assertion in `itertoolsmodule.c: itertools_count_impl` for `count(sys.maxsize)`

```python

```

- Issue Number: 126595
- Date filed: 08/11/2024
- Date closed: 12/11/2024
- Kind: Abort/AssertionError
- Configuration:
- Python versions: 3.12;3.13;3.14
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 17- [126644](https://github.com/python/cpython/issues/126644) - `_interpreters` is not thread safe on the free-threaded build

```python

```

- Issue Number: 126644
- Date filed: 10/11/2024
- Date closed: 11/01/2025
- Kind: 
- Configuration:
- Python versions: 3.13;3.14
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 18- [126654](https://github.com/python/cpython/issues/126654) - `_interpreters.exec` with invalid parameters segfaults

```python

```

- Issue Number: 126654
- Date filed: 10/11/2024
- Date closed: 11/11/2024
- Kind: Segfault/Crash
- Configuration:
- Python versions: 
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 19- [126876](https://github.com/python/cpython/issues/126876) - Assertion failure for `socket` with too large default timeout (larger than INT_MAX)

```python

```

- Issue Number: 126876
- Date filed: 15/11/2024
- Date closed: 14/12/2024
- Kind: Abort/AssertionError
- Configuration:
- Python versions: 3.12;3.13;3.14
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 20- [126881](https://github.com/python/cpython/issues/126881) - Segfault with `asyncio.base_events.BaseEventLoop` when passed a small float to `set_debug`.

```python

```

- Issue Number: 126881
- Date filed: 15/11/2024
- Date closed: 29/11/2024
- Kind: Segfault/Crash
- Configuration:
- Python versions: 3.12;3.13;3.14
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 21- [126884](https://github.com/python/cpython/issues/126884) - Calling `cProfile.runctx` in threads on a free-threading build segfaults

```python

```

- Issue Number: 126884
- Date filed: 15/11/2024
- Date closed: 
- Kind: Segfault/Crash
- Configuration:
- Python versions: 3.13;3.14
- Status: open
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 22- [126895](https://github.com/python/cpython/issues/126895) - Segfault/aborts calling `readline.set_completer_delims` in threads in a free-threaded build

```python

```

- Issue Number: 126895
- Date filed: 16/11/2024
- Date closed: 17/03/2025
- Kind: Segfault/Crash
- Configuration:
- Python versions: 3.13;3.14
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 23- [126907](https://github.com/python/cpython/issues/126907) - Running `atexit` from threads in free-threading build segfaults

```python

```

- Issue Number: 126907
- Date filed: 16/11/2024
- Date closed: 16/12/2024
- Kind: Segfault/Crash
- Configuration:
- Python versions: 3.13;3.14
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 24- [127085](https://github.com/python/cpython/issues/127085) - Calling `ShareableList.count` in threads aborts: `Assertion 'self->exports == 0' failed`

```python

```

- Issue Number: 127085
- Date filed: 21/11/2024
- Date closed: 16/12/2024
- Kind: Abort/AssertionError
- Configuration:
- Python versions: 3.13;3.14
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 25- [127165](https://github.com/python/cpython/issues/127165) - Segfault in invalid `concurrent.futures.interpreter.WorkerContext`

```python

```

- Issue Number: 127165
- Date filed: 22/11/2024
- Date closed: 01/12/2024
- Kind: Segfault/Crash
- Configuration:
- Python versions: 3.13;3.14
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 26- [127182](https://github.com/python/cpython/issues/127182) - Assertion failure from `StringIO.__setstate__`

```python

```

- Issue Number: 127182
- Date filed: 23/11/2024
- Date closed: 25/11/2024
- Kind: Abort/AssertionError
- Configuration:
- Python versions: 3.13;3.14
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 27- [127190](https://github.com/python/cpython/issues/127190) - Segfault from `asyncio.events._running_loop.__setattr__` with invalid name

```python

```

- Issue Number: 127190
- Date filed: 23/11/2024
- Date closed: 28/11/2024
- Kind: Segfault/Crash
- Configuration:
- Python versions: 3.13;3.14
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 28- [127192](https://github.com/python/cpython/issues/127192) - Segfault or abort in free-threaded build calling methods from exception in threads

```python

```

- Issue Number: 127192
- Date filed: 23/11/2024
- Date closed: 23/11/2024
- Kind: Segfault/Crash
- Configuration:
- Python versions: 3.13;3.14
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 29- [127196](https://github.com/python/cpython/issues/127196) - `_interpreters.exec` with invalid dict as `shared` segfaults

```python

```

- Issue Number: 127196
- Date filed: 23/11/2024
- Date closed: 09/01/2025
- Kind: Segfault/Crash
- Configuration:
- Python versions: 3.13;3.14
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 30- [127208](https://github.com/python/cpython/issues/127208) - `ExtensionFileLoader.load_module` aborts when initialized with a path containing null-bytes

```python

```

- Issue Number: 127208
- Date filed: 24/11/2024
- Date closed: 29/11/2024
- Kind: Abort/AssertionError
- Configuration:
- Python versions: 3.12;3.13;3.14
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 31- [127234](https://github.com/python/cpython/issues/127234) - Assertion failures from `_interpchannels._register_end_types` 

```python

```

- Issue Number: 127234
- Date filed: 24/11/2024
- Date closed: 
- Kind: Abort/AssertionError
- Configuration:
- Python versions: 3.13;3.14
- Status: open
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 32- [127235](https://github.com/python/cpython/issues/127235) - Failed assertion in `Python/legacy_tracing.c:431` on a free-threading build

```python

```

- Issue Number: 127235
- Date filed: 24/11/2024
- Date closed: 
- Kind: Abort/AssertionError
- Configuration:
- Python versions: 
- Status: open
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 33- [127316](https://github.com/python/cpython/issues/127316) - [FreeThreading] object_set_class() fails with an assertion error in _PyCriticalSection_AssertHeld()

```python

```

- Issue Number: 127316
- Date filed: 27/11/2024
- Date closed: 29/11/2024
- Kind: Abort/AssertionError
- Configuration:
- Python versions: 
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 34- [127603](https://github.com/python/cpython/issues/127603) - Abort from `GenericAlias.__sizeof__`: `ob->ob_type != &PyLong_Type`

```python

```

- Issue Number: 127603
- Date filed: 04/12/2024
- Date closed: 11/12/2024
- Kind: Abort/AssertionError
- Configuration:
- Python versions: 3.12
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 35- [127836](https://github.com/python/cpython/issues/127836) - Assertion failure on finalization with `_lsprof` and `asyncio` in 3.12

```python

```

- Issue Number: 127836
- Date filed: 11/12/2024
- Date closed: 23/02/2025
- Kind: Abort/AssertionError
- Configuration:
- Python versions: 3.12
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 36- [127870](https://github.com/python/cpython/issues/127870) - Segfaults in ctypes _as_parameter_ handling when called with `MagicMock`

```python

```

- Issue Number: 127870
- Date filed: 12/12/2024
- Date closed: 13/12/2024
- Kind: Segfault/Crash
- Configuration:
- Python versions: 
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 37- [129573](https://github.com/python/cpython/issues/129573) - Failed assertion in `_PyUnicode_Equal` from `calculate_suggestions` with non-string candidate

```python

```

- Issue Number: 129573
- Date filed: 02/02/2025
- Date closed: 
- Kind: Abort/AssertionError
- Configuration:
- Python versions: 3.12;3.13;3.14
- Status: open
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 38- [129766](https://github.com/python/cpython/issues/129766) - Fatal Python error from `warnings._release_lock()`

```python

```

- Issue Number: 129766
- Date filed: 07/02/2025
- Date closed: 07/02/2025
- Kind: Fatal Python Error
- Configuration:
- Python versions: 
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 39- [131580](https://github.com/python/cpython/issues/131580) - Faulthandler segfaults when called from threads

```python

```

- Issue Number: 131580
- Date filed: 22/03/2025
- Date closed: 25/03/2025
- Kind: Segfault/Crash
- Configuration:
- Python versions: 
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 40- [131998](https://github.com/python/cpython/issues/131998) - The interpreter crashes when specializing bound method calls on unbound objects

```python

```

- Issue Number: 131998
- Date filed: 02/04/2025
- Date closed: 08/04/2025
- Kind: Segfault/Crash
- Configuration:
- Python versions: 3.13;3.14
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 41- [132002](https://github.com/python/cpython/issues/132002) - Segfault deallocating a `ContextVar` built with `str` subclass

```python

```

- Issue Number: 132002
- Date filed: 02/04/2025
- Date closed: 02/04/2025
- Kind: Segfault/Crash
- Configuration:
- Python versions: 3.12;3.13;3.14
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 42- [132011](https://github.com/python/cpython/issues/132011) - Failed assertion in `_PyEval_EvalFrameDefault`: `self_o != NULL`

```python

```

- Issue Number: 132011
- Date filed: 02/04/2025
- Date closed: 06/04/2025
- Kind: Abort/AssertionError
- Configuration:
- Python versions: 
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 43- [132171](https://github.com/python/cpython/issues/132171) - Assertion failure calling `_interpreters.run_string` with a string subclass instance

```python

```

- Issue Number: 132171
- Date filed: 06/04/2025
- Date closed: 07/04/2025
- Kind: Abort/AssertionError
- Configuration:
- Python versions: 
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 44- [132176](https://github.com/python/cpython/issues/132176) - Abort when using a tuple subclass instance as the `bases` parameter for `type`

```python

```

- Issue Number: 132176
- Date filed: 06/04/2025
- Date closed: 15/04/2025
- Kind: Abort/AssertionError
- Configuration:
- Python versions: 
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 45- [132250](https://github.com/python/cpython/issues/132250) - `_ccall_callback` method of `_lsprof.Profiler` causes Fatal Python error

```python

```

- Issue Number: 132250
- Date filed: 08/04/2025
- Date closed: 08/04/2025
- Kind: Fatal Python Error
- Configuration:
- Python versions: 
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 46- [132296](https://github.com/python/cpython/issues/132296) - Concurrent deallocation of threads while calling `PyEval_SetTrace`

```python

```

- Issue Number: 132296
- Date filed: 09/04/2025
- Date closed: 
- Kind: 
- Configuration:
- Python versions: 
- Status: open
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 47- [132386](https://github.com/python/cpython/issues/132386) - Segfault or failed assertion (`obj != NULL`) in `PyStackRef_FromPyObjectSteal`

```python

```

- Issue Number: 132386
- Date filed: 11/04/2025
- Date closed: 11/04/2025
- Kind: Segfault/Crash
- Configuration:
- Python versions: 
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 48- [132461](https://github.com/python/cpython/issues/132461) - Abort from calling `OrderedDict.setdefault` with an invalid value

```python

```

- Issue Number: 132461
- Date filed: 13/04/2025
- Date closed: 
- Kind: Abort/AssertionError
- Configuration:
- Python versions: 
- Status: open
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 49- [132551](https://github.com/python/cpython/issues/132551) - Segfault/abort from calling `BytesIO` `unshare_buffer` in threads on a free-threaded build

```python

```

- Issue Number: 132551
- Date filed: 15/04/2025
- Date closed: 08/05/2025
- Kind: Segfault/Crash
- Configuration:
- Python versions: 3.13;3.14
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 50- [132707](https://github.com/python/cpython/issues/132707) - Segfault in free-threaded build from interaction of nested list/tuple repr

```python

```

- Issue Number: 132707
- Date filed: 18/04/2025
- Date closed: 18/04/2025
- Kind: Segfault/Crash
- Configuration:
- Python versions: 
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 51- [132713](https://github.com/python/cpython/issues/132713) - Segfault in `union_repr` from `list_repr_impl` in free-threaded build

```python

```

- Issue Number: 132713
- Date filed: 19/04/2025
- Date closed: 23/04/2025
- Kind: Segfault/Crash
- Configuration:
- Python versions: 3.13;3.14
- Status: closed
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------


#### 52- [133441](https://github.com/python/cpython/issues/133441) - 3.13: Abort from failed assertion in `_PyEval_EvalFrameDefault`

```python

```

- Issue Number: 133441
- Date filed: 05/05/2025
- Date closed: 
- Kind: Abort/AssertionError
- Configuration:
- Python versions: 3.13
- Status: open
- PRs (author):
  - []() ()

<details><summary>Backtrace/error message:</summary>
<p>


```shell

```
</p>
</details>

----------

