Number;Issue #;Title;HTML URL;Heading;Date Filed;Week;Status;Closed Date;Labels;Assignees;Guessed Kind;Guessed CPython Versions
1;126219;`tkinter.Tk` segfault with invalid `className`;https://github.com/python/cpython/issues/126219;#### 1- [126219](https://github.com/python/cpython/issues/126219) - `tkinter.Tk` segfault with invalid `className`;31/10/2024;44;open;;"extension-modules;topic-tkinter;type-crash;3.12;3.13;3.14";;Segfault/Crash;"3.12;3.13;3.14"
2;126220;`_lsprof.Profiler._creturn_callback()` segfaults;https://github.com/python/cpython/issues/126220;#### 2- [126220](https://github.com/python/cpython/issues/126220) - `_lsprof.Profiler._creturn_callback()` segfaults;31/10/2024;44;closed;06/11/2024;"extension-modules;type-crash;3.12;3.13;3.14";sobolevn;Segfault/Crash;"3.12;3.13;3.14"
3;126221;`sre_constants._makecodes` segfaults in JIT builds;https://github.com/python/cpython/issues/126221;#### 3- [126221](https://github.com/python/cpython/issues/126221) - `sre_constants._makecodes` segfaults in JIT builds;31/10/2024;44;closed;31/10/2024;"interpreter-core;type-crash;topic-JIT";;Segfault/Crash;
4;126223;`SystemError` caused by `_interpreters.create()` with invalid unicode argument;https://github.com/python/cpython/issues/126223;#### 4- [126223](https://github.com/python/cpython/issues/126223) - `SystemError` caused by `_interpreters.create()` with invalid unicode argument;31/10/2024;44;closed;31/10/2024;"type-bug;extension-modules;topic-subinterpreters;3.13;3.14";;SystemError;"3.13;3.14"
5;126312;GC aborts in debug no-gil build;https://github.com/python/cpython/issues/126312;#### 5- [126312](https://github.com/python/cpython/issues/126312) - GC aborts in debug no-gil build;01/11/2024;44;closed;15/11/2024;"extension-modules;type-crash;3.13;topic-free-threading;3.14";;Abort/AssertionError;"3.13;3.14"
6;126313;`curses.napms()` aborts with a `SystemError`;https://github.com/python/cpython/issues/126313;#### 6- [126313](https://github.com/python/cpython/issues/126313) - `curses.napms()` aborts with a `SystemError`;01/11/2024;44;closed;04/11/2024;"extension-modules;type-crash;3.13;3.14";picnixz;Abort/AssertionError;"3.13;3.14"
7;126314;Running `tracemalloc` in threads segfaults on no-gil;https://github.com/python/cpython/issues/126314;#### 7- [126314](https://github.com/python/cpython/issues/126314) - Running `tracemalloc` in threads segfaults on no-gil;01/11/2024;44;closed;14/03/2025;"interpreter-core;type-crash;3.13;topic-free-threading;3.14";;Segfault/Crash;"3.13;3.14"
8;126315;`tracemalloc` aborts when run from threads in no-gil;https://github.com/python/cpython/issues/126315;#### 8- [126315](https://github.com/python/cpython/issues/126315) - `tracemalloc` aborts when run from threads in no-gil;01/11/2024;44;open;;"interpreter-core;type-crash;3.13;topic-free-threading;3.14";;Abort/AssertionError;"3.13;3.14"
9;126316;`grp` is not thread safe;https://github.com/python/cpython/issues/126316;#### 9- [126316](https://github.com/python/cpython/issues/126316) - `grp` is not thread safe;01/11/2024;44;closed;21/11/2024;"extension-modules;type-crash;topic-subinterpreters;3.13;topic-free-threading;3.14";;;"3.13;3.14"
10;126341;`SystemError` from calling `__iter__` on a released `memoryview`;https://github.com/python/cpython/issues/126341;#### 10- [126341](https://github.com/python/cpython/issues/126341) - `SystemError` from calling `__iter__` on a released `memoryview`;03/11/2024;45;closed;13/11/2024;"interpreter-core;easy;type-crash;3.12;3.13;3.14";ritvikpasham;SystemError;"3.12;3.13;3.14"
11;126366;Abort in free-threaded build due to mutation of `ChainMap` of a `Counter` in threads;https://github.com/python/cpython/issues/126366;#### 11- [126366](https://github.com/python/cpython/issues/126366) - Abort in free-threaded build due to mutation of `ChainMap` of a `Counter` in threads;03/11/2024;45;closed;18/04/2025;"interpreter-core;type-crash;3.13;topic-free-threading;3.14";;Abort/AssertionError;"3.13;3.14"
12;126455;Calling many methods on `_ssl._SSLSocket()` segfaults;https://github.com/python/cpython/issues/126455;#### 12- [126455](https://github.com/python/cpython/issues/126455) - Calling many methods on `_ssl._SSLSocket()` segfaults;05/11/2024;45;closed;06/11/2024;"extension-modules;type-crash;topic-SSL;3.12;3.13;3.14";ZeroIntensity;Segfault/Crash;"3.12;3.13;3.14"
13;126456;`_pyrepl._minimal_curses.tigetstr` segfaults;https://github.com/python/cpython/issues/126456;#### 13- [126456](https://github.com/python/cpython/issues/126456) - `_pyrepl._minimal_curses.tigetstr` segfaults;05/11/2024;45;closed;13/11/2024;"type-crash;3.13;3.14;topic-repl";;Segfault/Crash;"3.13;3.14"
14;126461;Calling `_pickle.load` with a `MagicMock` results in `SystemError`/aborts;https://github.com/python/cpython/issues/126461;#### 14- [126461](https://github.com/python/cpython/issues/126461) - Calling `_pickle.load` with a `MagicMock` results in `SystemError`/aborts;05/11/2024;45;closed;06/11/2024;"extension-modules;type-crash;3.12;3.13;3.14";;Abort/AssertionError;"3.12;3.13;3.14"
15;126594;"Failed assertion in typeobject.c::wrap_buffer for `b"""".__buffer__(-2**31 - 1)`";https://github.com/python/cpython/issues/126594;"#### 15- [126594](https://github.com/python/cpython/issues/126594) - Failed assertion in typeobject.c::wrap_buffer for `b"""".__buffer__(-2**31 - 1)`";08/11/2024;45;closed;24/11/2024;"interpreter-core;type-crash;3.12;3.13;3.14";JelleZijlstra;Abort/AssertionError;"3.12;3.13;3.14"
16;126595;Failed assertion in `itertoolsmodule.c: itertools_count_impl` for `count(sys.maxsize)`;https://github.com/python/cpython/issues/126595;#### 16- [126595](https://github.com/python/cpython/issues/126595) - Failed assertion in `itertoolsmodule.c: itertools_count_impl` for `count(sys.maxsize)`;08/11/2024;45;closed;12/11/2024;"interpreter-core;type-crash;3.12;3.13;3.14";picnixz;Abort/AssertionError;"3.12;3.13;3.14"
17;126644;`_interpreters` is not thread safe on the free-threaded build;https://github.com/python/cpython/issues/126644;#### 17- [126644](https://github.com/python/cpython/issues/126644) - `_interpreters` is not thread safe on the free-threaded build;10/11/2024;46;closed;11/01/2025;"extension-modules;type-crash;topic-subinterpreters;3.13;topic-free-threading;3.14";ZeroIntensity;;"3.13;3.14"
18;126654;`_interpreters.exec` with invalid parameters segfaults;https://github.com/python/cpython/issues/126654;#### 18- [126654](https://github.com/python/cpython/issues/126654) - `_interpreters.exec` with invalid parameters segfaults;10/11/2024;46;closed;11/11/2024;"extension-modules;type-crash;topic-subinterpreters";sobolevn;Segfault/Crash;
19;126876;Assertion failure for `socket` with too large default timeout (larger than INT_MAX);https://github.com/python/cpython/issues/126876;#### 19- [126876](https://github.com/python/cpython/issues/126876) - Assertion failure for `socket` with too large default timeout (larger than INT_MAX);15/11/2024;46;closed;14/12/2024;"extension-modules;type-crash;3.12;3.13;3.14";;Abort/AssertionError;"3.12;3.13;3.14"
20;126881;Segfault with `asyncio.base_events.BaseEventLoop` when passed a small float to `set_debug`.;https://github.com/python/cpython/issues/126881;#### 20- [126881](https://github.com/python/cpython/issues/126881) - Segfault with `asyncio.base_events.BaseEventLoop` when passed a small float to `set_debug`.;15/11/2024;46;closed;29/11/2024;"interpreter-core;type-crash;3.12;3.13;3.14";kumaraditya303;Segfault/Crash;"3.12;3.13;3.14"
21;126884;Calling `cProfile.runctx` in threads on a free-threading build segfaults;https://github.com/python/cpython/issues/126884;#### 21- [126884](https://github.com/python/cpython/issues/126884) - Calling `cProfile.runctx` in threads on a free-threading build segfaults;15/11/2024;46;open;;"extension-modules;type-crash;3.13;topic-free-threading;3.14";;Segfault/Crash;"3.13;3.14"
22;126895;Segfault/aborts calling `readline.set_completer_delims` in threads in a free-threaded build;https://github.com/python/cpython/issues/126895;#### 22- [126895](https://github.com/python/cpython/issues/126895) - Segfault/aborts calling `readline.set_completer_delims` in threads in a free-threaded build;16/11/2024;46;closed;17/03/2025;"stdlib;extension-modules;type-crash;3.13;topic-free-threading;3.14";;Segfault/Crash;"3.13;3.14"
23;126907;Running `atexit` from threads in free-threading build segfaults;https://github.com/python/cpython/issues/126907;#### 23- [126907](https://github.com/python/cpython/issues/126907) - Running `atexit` from threads in free-threading build segfaults;16/11/2024;46;closed;16/12/2024;"extension-modules;type-crash;3.13;topic-free-threading;3.14";ZeroIntensity;Segfault/Crash;"3.13;3.14"
24;127085;Calling `ShareableList.count` in threads aborts: `Assertion 'self->exports == 0' failed`;https://github.com/python/cpython/issues/127085;#### 24- [127085](https://github.com/python/cpython/issues/127085) - Calling `ShareableList.count` in threads aborts: `Assertion 'self->exports == 0' failed`;21/11/2024;47;closed;16/12/2024;"interpreter-core;type-crash;topic-multiprocessing;3.13;topic-free-threading;3.14";;Abort/AssertionError;"3.13;3.14"
25;127165;Segfault in invalid `concurrent.futures.interpreter.WorkerContext`;https://github.com/python/cpython/issues/127165;#### 25- [127165](https://github.com/python/cpython/issues/127165) - Segfault in invalid `concurrent.futures.interpreter.WorkerContext`;22/11/2024;47;closed;01/12/2024;"extension-modules;type-crash;topic-subinterpreters;3.13;3.14";;Segfault/Crash;"3.13;3.14"
26;127182;Assertion failure from `StringIO.__setstate__`;https://github.com/python/cpython/issues/127182;#### 26- [127182](https://github.com/python/cpython/issues/127182) - Assertion failure from `StringIO.__setstate__`;23/11/2024;47;closed;25/11/2024;"extension-modules;type-crash;3.13;3.14";sobolevn;Abort/AssertionError;"3.13;3.14"
27;127190;Segfault from `asyncio.events._running_loop.__setattr__` with invalid name;https://github.com/python/cpython/issues/127190;#### 27- [127190](https://github.com/python/cpython/issues/127190) - Segfault from `asyncio.events._running_loop.__setattr__` with invalid name;23/11/2024;47;closed;28/11/2024;"extension-modules;type-crash;3.13;3.14";;Segfault/Crash;"3.13;3.14"
28;127192;Segfault or abort in free-threaded build calling methods from exception in threads;https://github.com/python/cpython/issues/127192;#### 28- [127192](https://github.com/python/cpython/issues/127192) - Segfault or abort in free-threaded build calling methods from exception in threads;23/11/2024;47;closed;23/11/2024;"interpreter-core;type-crash;3.13;topic-free-threading;3.14";;Segfault/Crash;"3.13;3.14"
29;127196;`_interpreters.exec` with invalid dict as `shared` segfaults;https://github.com/python/cpython/issues/127196;#### 29- [127196](https://github.com/python/cpython/issues/127196) - `_interpreters.exec` with invalid dict as `shared` segfaults;23/11/2024;47;closed;09/01/2025;"extension-modules;type-crash;topic-subinterpreters;3.13;3.14";sobolevn;Segfault/Crash;"3.13;3.14"
30;127208;`ExtensionFileLoader.load_module` aborts when initialized with a path containing null-bytes;https://github.com/python/cpython/issues/127208;#### 30- [127208](https://github.com/python/cpython/issues/127208) - `ExtensionFileLoader.load_module` aborts when initialized with a path containing null-bytes;24/11/2024;48;closed;29/11/2024;"interpreter-core;type-crash;topic-importlib;3.12;3.13;3.14";;Abort/AssertionError;"3.12;3.13;3.14"
31;127234;Assertion failures from `_interpchannels._register_end_types` ;https://github.com/python/cpython/issues/127234;#### 31- [127234](https://github.com/python/cpython/issues/127234) - Assertion failures from `_interpchannels._register_end_types` ;24/11/2024;48;open;;"extension-modules;type-crash;topic-subinterpreters;3.13;3.14";;Abort/AssertionError;"3.13;3.14"
32;127235;Failed assertion in `Python/legacy_tracing.c:431` on a free-threading build;https://github.com/python/cpython/issues/127235;#### 32- [127235](https://github.com/python/cpython/issues/127235) - Failed assertion in `Python/legacy_tracing.c:431` on a free-threading build;24/11/2024;48;open;;"type-crash;topic-free-threading";;Abort/AssertionError;
33;127316;[FreeThreading] object_set_class() fails with an assertion error in _PyCriticalSection_AssertHeld();https://github.com/python/cpython/issues/127316;#### 33- [127316](https://github.com/python/cpython/issues/127316) - [FreeThreading] object_set_class() fails with an assertion error in _PyCriticalSection_AssertHeld();27/11/2024;48;closed;29/11/2024;"interpreter-core;type-crash;topic-free-threading";kumaraditya303;Abort/AssertionError;
34;127603;Abort from `GenericAlias.__sizeof__`: `ob->ob_type != &PyLong_Type`;https://github.com/python/cpython/issues/127603;#### 34- [127603](https://github.com/python/cpython/issues/127603) - Abort from `GenericAlias.__sizeof__`: `ob->ob_type != &PyLong_Type`;04/12/2024;49;closed;11/12/2024;"interpreter-core;type-crash;3.12";;Abort/AssertionError;3.12
35;127836;Assertion failure on finalization with `_lsprof` and `asyncio` in 3.12;https://github.com/python/cpython/issues/127836;#### 35- [127836](https://github.com/python/cpython/issues/127836) - Assertion failure on finalization with `_lsprof` and `asyncio` in 3.12;11/12/2024;50;closed;23/02/2025;"topic-asyncio;type-crash;3.12";;Abort/AssertionError;3.12
36;127870;Segfaults in ctypes _as_parameter_ handling when called with `MagicMock`;https://github.com/python/cpython/issues/127870;#### 36- [127870](https://github.com/python/cpython/issues/127870) - Segfaults in ctypes _as_parameter_ handling when called with `MagicMock`;12/12/2024;50;closed;13/12/2024;"topic-ctypes;type-crash";;Segfault/Crash;
37;129573;Failed assertion in `_PyUnicode_Equal` from `calculate_suggestions` with non-string candidate;https://github.com/python/cpython/issues/129573;#### 37- [129573](https://github.com/python/cpython/issues/129573) - Failed assertion in `_PyUnicode_Equal` from `calculate_suggestions` with non-string candidate;02/02/2025;6;open;;"interpreter-core;type-crash;3.12;3.13;3.14";;Abort/AssertionError;"3.12;3.13;3.14"
38;129766;Fatal Python error from `warnings._release_lock()`;https://github.com/python/cpython/issues/129766;#### 38- [129766](https://github.com/python/cpython/issues/129766) - Fatal Python error from `warnings._release_lock()`;07/02/2025;6;closed;07/02/2025;type-crash;sobolevn;Fatal Python Error;
39;131580;Faulthandler segfaults when called from threads;https://github.com/python/cpython/issues/131580;#### 39- [131580](https://github.com/python/cpython/issues/131580) - Faulthandler segfaults when called from threads;22/03/2025;12;closed;25/03/2025;"extension-modules;type-crash";;Segfault/Crash;
40;131998;The interpreter crashes when specializing bound method calls on unbound objects;https://github.com/python/cpython/issues/131998;#### 40- [131998](https://github.com/python/cpython/issues/131998) - The interpreter crashes when specializing bound method calls on unbound objects;02/04/2025;14;closed;08/04/2025;"interpreter-core;release-blocker;type-crash;3.13;3.14";;Segfault/Crash;"3.13;3.14"
41;132002;Segfault deallocating a `ContextVar` built with `str` subclass;https://github.com/python/cpython/issues/132002;#### 41- [132002](https://github.com/python/cpython/issues/132002) - Segfault deallocating a `ContextVar` built with `str` subclass;02/04/2025;14;closed;02/04/2025;"extension-modules;type-crash;3.12;3.13;3.14";sobolevn;Segfault/Crash;"3.12;3.13;3.14"
42;132011;Failed assertion in `_PyEval_EvalFrameDefault`: `self_o != NULL`;https://github.com/python/cpython/issues/132011;#### 42- [132011](https://github.com/python/cpython/issues/132011) - Failed assertion in `_PyEval_EvalFrameDefault`: `self_o != NULL`;02/04/2025;14;closed;06/04/2025;"interpreter-core;type-crash";sobolevn;Abort/AssertionError;
43;132171;Assertion failure calling `_interpreters.run_string` with a string subclass instance;https://github.com/python/cpython/issues/132171;#### 43- [132171](https://github.com/python/cpython/issues/132171) - Assertion failure calling `_interpreters.run_string` with a string subclass instance;06/04/2025;15;closed;07/04/2025;"extension-modules;type-crash;topic-subinterpreters";sobolevn;Abort/AssertionError;
44;132176;Abort when using a tuple subclass instance as the `bases` parameter for `type`;https://github.com/python/cpython/issues/132176;#### 44- [132176](https://github.com/python/cpython/issues/132176) - Abort when using a tuple subclass instance as the `bases` parameter for `type`;06/04/2025;15;closed;15/04/2025;"interpreter-core;type-crash";sobolevn;Abort/AssertionError;
45;132250;`_ccall_callback` method of `_lsprof.Profiler` causes Fatal Python error;https://github.com/python/cpython/issues/132250;#### 45- [132250](https://github.com/python/cpython/issues/132250) - `_ccall_callback` method of `_lsprof.Profiler` causes Fatal Python error;08/04/2025;15;closed;08/04/2025;"extension-modules;type-crash";;Fatal Python Error;
46;132296;Concurrent deallocation of threads while calling `PyEval_SetTrace`;https://github.com/python/cpython/issues/132296;#### 46- [132296](https://github.com/python/cpython/issues/132296) - Concurrent deallocation of threads while calling `PyEval_SetTrace`;09/04/2025;15;open;;"interpreter-core;type-crash;topic-C-API;topic-free-threading";;;
47;132386;Segfault or failed assertion (`obj != NULL`) in `PyStackRef_FromPyObjectSteal`;https://github.com/python/cpython/issues/132386;#### 47- [132386](https://github.com/python/cpython/issues/132386) - Segfault or failed assertion (`obj != NULL`) in `PyStackRef_FromPyObjectSteal`;11/04/2025;15;closed;11/04/2025;"interpreter-core;type-crash";tomasr8;Segfault/Crash;
48;132461;Abort from calling `OrderedDict.setdefault` with an invalid value;https://github.com/python/cpython/issues/132461;#### 48- [132461](https://github.com/python/cpython/issues/132461) - Abort from calling `OrderedDict.setdefault` with an invalid value;13/04/2025;16;open;;"interpreter-core;type-crash";;Abort/AssertionError;
49;132551;Segfault/abort from calling `BytesIO` `unshare_buffer` in threads on a free-threaded build;https://github.com/python/cpython/issues/132551;#### 49- [132551](https://github.com/python/cpython/issues/132551) - Segfault/abort from calling `BytesIO` `unshare_buffer` in threads on a free-threaded build;15/04/2025;16;closed;08/05/2025;"extension-modules;type-crash;3.13;topic-free-threading;3.14";;Segfault/Crash;"3.13;3.14"
50;132707;Segfault in free-threaded build from interaction of nested list/tuple repr;https://github.com/python/cpython/issues/132707;#### 50- [132707](https://github.com/python/cpython/issues/132707) - Segfault in free-threaded build from interaction of nested list/tuple repr;18/04/2025;16;closed;18/04/2025;"interpreter-core;type-crash;topic-free-threading";;Segfault/Crash;
51;132713;Segfault in `union_repr` from `list_repr_impl` in free-threaded build;https://github.com/python/cpython/issues/132713;#### 51- [132713](https://github.com/python/cpython/issues/132713) - Segfault in `union_repr` from `list_repr_impl` in free-threaded build;19/04/2025;16;closed;23/04/2025;"interpreter-core;type-crash;topic-typing;3.13;topic-free-threading;3.14";sobolevn;Segfault/Crash;"3.13;3.14"
52;133441;3.13: Abort from failed assertion in `_PyEval_EvalFrameDefault`;https://github.com/python/cpython/issues/133441;#### 52- [133441](https://github.com/python/cpython/issues/133441) - 3.13: Abort from failed assertion in `_PyEval_EvalFrameDefault`;05/05/2025;19;open;;"interpreter-core;type-crash;3.13";;Abort/AssertionError;3.13
